add shorebird relee workflow

diff --git a/.github/workflows/shorebird_release.yml b/.github/workflows/shorebird_release.yml
--- a/.github/workflows/shorebird_release.yml
+++ b/.github/workflows/shorebird_release.yml
@@ -7,6 +7,7 @@ on:
 
 env:
   SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
+  FLUTTER_VERSION: '3.47.4'
 
 jobs:
   release:
@@ -33,7 +34,24 @@ jobs:
         run: |
           printf '%s\n' "$ENV_FILE" > .env
 
+      - name: Generate code
+        run: |
+          FLUTTER_BIN=$(find "$HOME/.config/shorebird" -path "*/bin/flutter" -type f | head -1)
+
+          if [ -z "$FLUTTER_BIN" ]; then
+            echo "Flutter binary not found in Shorebird cache."
+            exit 1
+          fi
+
+          FLUTTER_DIR=$(dirname "$FLUTTER_BIN")
+
+          echo "Using Flutter: $FLUTTER_BIN"
+
+          "$FLUTTER_BIN" pub get
+          "$FLUTTER_DIR/dart" run build_runner build --delete-conflicting-outputs
+
       - name: Shorebird Release
         uses: shorebirdtech/shorebird-release@v1
         with:
           platform: android
+          flutter-version: ${{ env.FLUTTER_VERSION }}
